# Generated by Django 5.0.1 on 2024-01-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="ratings",
            field=models.IntegerField(default=0),
        ),
    ]
