# Generated by Django 5.0.1 on 2024-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DishThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(upload_to="dishes", verbose_name="dish image"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="images",
            field=models.ManyToManyField(
                related_name="dish_images", to="app.dishthumbnail"
            ),
        ),
    ]
