# Generated by Django 5.0.1 on 2024-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
