# Generated by Django 5.0.1 on 2024-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_driver_vehicle_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="vehicle_image",
            field=models.ImageField(
                null=True, upload_to="driver/", verbose_name="vehicle image"
            ),
        ),
    ]
