# Generated by Django 5.0.1 on 2024-01-13 00:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_dish_ratings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteDish",
            new_name="FavouriteDish",
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name": "Cart Item", "verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterModelOptions(
            name="deliverystatus",
            options={
                "verbose_name": "Delivery Status",
                "verbose_name_plural": "Delivery Status",
            },
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.AlterModelOptions(
            name="favouritedish",
            options={
                "verbose_name": "Favourite Dish",
                "verbose_name_plural": "Favourite Dishes",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments"},
        ),
        migrations.AlterModelOptions(
            name="personalmessage",
            options={
                "verbose_name": "Personal Message",
                "verbose_name_plural": "Personal Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "verbose_name": "Restaurant",
                "verbose_name_plural": "Restaurants",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Shopping Cart"},
        ),
    ]
