# Generated by Django 5.0.3 on 2024-03-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_dish_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True,
                default=1,
                upload_to="restaurant/",
                verbose_name="restauarant image",
            ),
            preserve_default=False,
        ),
    ]
