# Generated by Django 5.0.3 on 2024-03-30 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_restaurantwithdrawal_account_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantwithdrawal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant_user_withdrawal",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
