# Generated by Django 5.0.3 on 2024-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_restaurant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="dish_images", to="app.image"
            ),
        ),
    ]
