# Generated by Django 5.0.1 on 2024-01-13 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_favoritedish_favouritedish_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="favourite",
            field=models.ManyToManyField(
                related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.driver",
            ),
        ),
        migrations.DeleteModel(
            name="FavouriteDish",
        ),
    ]
