# Generated by Django 5.0.1 on 2024-01-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_dish_favourite_alter_order_assigned_driver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
