# Generated by Django 5.0.1 on 2024-02-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_dish_restaurant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="food_item",
            new_name="dish_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="assigned_driver",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="assigned_driver_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.driver",
            ),
        ),
    ]
