# Generated by Django 5.0.1 on 2024-01-13 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="categories",
        ),
        migrations.AddField(
            model_name="dish",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_category",
                to="app.category",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="dish",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="dish",
            name="restaurant",
            field=models.ManyToManyField(
                related_name="restaurants", to="app.restaurant"
            ),
        ),
    ]
