# Generated by Django 5.0.1 on 2024-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_food_item_orderitem_dish_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
