# Generated by Django 5.0.1 on 2024-01-13 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_restaurant_categories_dish_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="favourite",
            field=models.ManyToManyField(
                blank=True, related_name="favourites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="restaurant",
            field=models.ManyToManyField(
                blank=True, related_name="restaurants", to="app.restaurant"
            ),
        ),
    ]
