# Generated by Django 5.0.1 on 2024-02-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_orderitem_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="dish_id",
            new_name="dish",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="assigned_driver_id",
            new_name="driver",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.restaurant",
            ),
        ),
    ]
