# Generated by Django 5.0.1 on 2024-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_dish_favourite_alter_dish_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
