# Generated by Django 5.0.1 on 2024-02-06 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_dish_id_orderitem_dish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tracking_url",
        ),
    ]
