# Generated by Django 5.0.1 on 2024-02-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_order_tracking_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "delivered"),
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.BooleanField(default=False, verbose_name="Has Paid?"),
        ),
    ]
