# Generated by Django 5.0.1 on 2024-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_orderitem_status_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.IntegerField(),
        ),
    ]
