# Generated by Django 5.0.1 on 2024-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_order_total_price_alter_orderitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
