# Generated by Django 5.0.1 on 2024-02-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
