# Generated by Django 5.0.1 on 2024-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="labelled_place",
            field=models.CharField(
                choices=[("HOME", "HOME"), ("WORK", "WORK"), ("OTHER", "OTHER")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
