# Generated by Django 5.0.1 on 2024-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "customer"),
                    ("chef", "chef"),
                    ("logistics", "logistics"),
                ],
                default="customer",
                max_length=10,
                verbose_name="Who Am I?",
            ),
        ),
    ]
