# Generated by Django 5.0.1 on 2024-01-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
