# Generated by Django 5.0.1 on 2024-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_useraddress_labelled_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="apartment",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="post_code",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="street",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
