# Generated by Django 5.0.1 on 2024-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[
                    ("email", "email"),
                    ("google", "google"),
                    ("facebook", "facebook"),
                    ("twitter", "twitter"),
                ],
                default="email",
                max_length=10,
            ),
        ),
    ]
